import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

const projectRoot = fileURLToPath(new URL(".", import.meta.url));

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        home: resolve(projectRoot, "index.html"),
        games: resolve(projectRoot, "games/index.html"),
        app: resolve(projectRoot, "app/index.html"),
        howToPlay: resolve(projectRoot, "how-to-play/index.html"),
        mobile: resolve(projectRoot, "mobile/index.html"),
        voicePacks: resolve(projectRoot, "voice-packs/index.html"),
        microphoneNotWorking: resolve(projectRoot, "microphone-not-working/index.html"),
        isItSafe: resolve(projectRoot, "is-it-safe/index.html"),
        alternatives: resolve(projectRoot, "alternatives/index.html"),
        gameplay: resolve(projectRoot, "gameplay/index.html"),
        multiplayer: resolve(projectRoot, "multiplayer/index.html"),
        pitchMatchingExercises: resolve(projectRoot, "pitch-matching-exercises/index.html"),
        vocalTimingExercises: resolve(projectRoot, "vocal-timing-exercises/index.html"),
        voiceGamesForParties: resolve(projectRoot, "voice-games-for-parties/index.html"),
        voiceImitationExercises: resolve(projectRoot, "voice-imitation-exercises/index.html"),
        voiceActingWarmUps: resolve(projectRoot, "voice-acting-warm-ups/index.html"),
        voiceProjectionExercises: resolve(projectRoot, "voice-projection-exercises/index.html"),
        voiceModulationExercises: resolve(projectRoot, "voice-modulation-exercises/index.html"),
        articulationExercisesForVoiceActing: resolve(projectRoot, "articulation-exercises-for-voice-acting/index.html"),
        characterVoiceExercises: resolve(projectRoot, "character-voice-exercises/index.html"),
        breathControlExercisesForVoiceActing: resolve(projectRoot, "breath-control-exercises-for-voice-acting/index.html"),
        voiceActingPracticeScripts: resolve(projectRoot, "voice-acting-practice-scripts/index.html"),
        emotionalVoiceActingExercises: resolve(projectRoot, "emotional-voice-acting-exercises/index.html"),
        voiceActingImprovExercises: resolve(projectRoot, "voice-acting-improv-exercises/index.html"),
        voiceActingAuditionExercises: resolve(projectRoot, "voice-acting-audition-exercises/index.html"),
        vocalCooldownExercises: resolve(projectRoot, "vocal-cooldown-exercises/index.html"),
        voiceActingScriptAnalysis: resolve(projectRoot, "voice-acting-script-analysis/index.html"),
        commercialVoiceActingExercises: resolve(projectRoot, "commercial-voice-acting-exercises/index.html"),
        voiceActingMicrophoneTechnique: resolve(projectRoot, "voice-acting-microphone-technique/index.html"),
        voiceActingSelfCritique: resolve(projectRoot, "voice-acting-self-critique/index.html"),
        voiceActingListeningExercises: resolve(projectRoot, "voice-acting-listening-exercises/index.html"),
        voiceActingColdReadingExercises: resolve(projectRoot, "voice-acting-cold-reading-exercises/index.html"),
        voiceActingSubtextExercises: resolve(projectRoot, "voice-acting-subtext-exercises/index.html"),
        voiceActingLineDeliveryExercises: resolve(projectRoot, "voice-acting-line-delivery-exercises/index.html"),
        voiceActingVocalStaminaExercises: resolve(projectRoot, "voice-acting-vocal-stamina-exercises/index.html"),
        voiceActingAccentExercises: resolve(projectRoot, "voice-acting-accent-exercises/index.html"),
        voiceActingPhysicalityExercises: resolve(projectRoot, "voice-acting-physicality-exercises/index.html"),
        voiceActingVisualizationExercises: resolve(projectRoot, "voice-acting-visualization-exercises/index.html"),
        voiceActingComedyTimingExercises: resolve(projectRoot, "voice-acting-comedy-timing-exercises/index.html"),
        voiceActingCharacterSwitchingExercises: resolve(projectRoot, "voice-acting-character-switching-exercises/index.html"),
        audiobookNarrationExercises: resolve(projectRoot, "audiobook-narration-exercises/index.html"),
        voiceActingStatusExercises: resolve(projectRoot, "voice-acting-status-exercises/index.html"),
        voiceActingMemoryExercises: resolve(projectRoot, "voice-acting-memory-exercises/index.html"),
        voiceActingCharacterRelationshipExercises: resolve(projectRoot, "voice-acting-character-relationship-exercises/index.html"),
        voiceActingReactionExercises: resolve(projectRoot, "voice-acting-reaction-exercises/index.html"),
        voiceActingEffortSoundsExercises: resolve(projectRoot, "voice-acting-effort-sounds-exercises/index.html"),
        voiceActingObjectiveExercises: resolve(projectRoot, "voice-acting-objective-exercises/index.html"),
        voiceActingStakesExercises: resolve(projectRoot, "voice-acting-stakes-exercises/index.html"),
        voiceActingTakingDirectionExercises: resolve(projectRoot, "voice-acting-taking-direction-exercises/index.html"),
        adrVoiceActingExercises: resolve(projectRoot, "adr-voice-acting-exercises/index.html"),
        eLearningNarrationExercises: resolve(projectRoot, "e-learning-narration-exercises/index.html"),
        about: resolve(projectRoot, "about/index.html"),
        contact: resolve(projectRoot, "contact/index.html"),
        privacy: resolve(projectRoot, "privacy/index.html"),
        terms: resolve(projectRoot, "terms/index.html"),
        zhHome: resolve(projectRoot, "zh/index.html"),
        zhGames: resolve(projectRoot, "zh/games/index.html"),
        zhApp: resolve(projectRoot, "zh/app/index.html"),
        zhHowToPlay: resolve(projectRoot, "zh/how-to-play/index.html"),
        zhMobile: resolve(projectRoot, "zh/mobile/index.html"),
        zhVoicePacks: resolve(projectRoot, "zh/voice-packs/index.html"),
        zhMicrophoneNotWorking: resolve(projectRoot, "zh/microphone-not-working/index.html"),
        zhIsItSafe: resolve(projectRoot, "zh/is-it-safe/index.html"),
        zhAlternatives: resolve(projectRoot, "zh/alternatives/index.html"),
        zhGameplay: resolve(projectRoot, "zh/gameplay/index.html"),
        zhMultiplayer: resolve(projectRoot, "zh/multiplayer/index.html"),
        zhPitchMatchingExercises: resolve(projectRoot, "zh/pitch-matching-exercises/index.html"),
        zhVocalTimingExercises: resolve(projectRoot, "zh/vocal-timing-exercises/index.html"),
        zhVoiceGamesForParties: resolve(projectRoot, "zh/voice-games-for-parties/index.html"),
        zhVoiceImitationExercises: resolve(projectRoot, "zh/voice-imitation-exercises/index.html"),
        zhVoiceActingWarmUps: resolve(projectRoot, "zh/voice-acting-warm-ups/index.html"),
        zhVoiceProjectionExercises: resolve(projectRoot, "zh/voice-projection-exercises/index.html"),
        zhVoiceModulationExercises: resolve(projectRoot, "zh/voice-modulation-exercises/index.html"),
        zhArticulationExercisesForVoiceActing: resolve(projectRoot, "zh/articulation-exercises-for-voice-acting/index.html"),
        zhCharacterVoiceExercises: resolve(projectRoot, "zh/character-voice-exercises/index.html"),
        zhBreathControlExercisesForVoiceActing: resolve(projectRoot, "zh/breath-control-exercises-for-voice-acting/index.html"),
        zhVoiceActingPracticeScripts: resolve(projectRoot, "zh/voice-acting-practice-scripts/index.html"),
        zhEmotionalVoiceActingExercises: resolve(projectRoot, "zh/emotional-voice-acting-exercises/index.html"),
        zhVoiceActingImprovExercises: resolve(projectRoot, "zh/voice-acting-improv-exercises/index.html"),
        zhVoiceActingAuditionExercises: resolve(projectRoot, "zh/voice-acting-audition-exercises/index.html"),
        zhVocalCooldownExercises: resolve(projectRoot, "zh/vocal-cooldown-exercises/index.html"),
        zhVoiceActingScriptAnalysis: resolve(projectRoot, "zh/voice-acting-script-analysis/index.html"),
        zhCommercialVoiceActingExercises: resolve(projectRoot, "zh/commercial-voice-acting-exercises/index.html"),
        zhVoiceActingMicrophoneTechnique: resolve(projectRoot, "zh/voice-acting-microphone-technique/index.html"),
        zhVoiceActingSelfCritique: resolve(projectRoot, "zh/voice-acting-self-critique/index.html"),
        zhVoiceActingListeningExercises: resolve(projectRoot, "zh/voice-acting-listening-exercises/index.html"),
        zhVoiceActingColdReadingExercises: resolve(projectRoot, "zh/voice-acting-cold-reading-exercises/index.html"),
        zhVoiceActingSubtextExercises: resolve(projectRoot, "zh/voice-acting-subtext-exercises/index.html"),
        zhVoiceActingLineDeliveryExercises: resolve(projectRoot, "zh/voice-acting-line-delivery-exercises/index.html"),
        zhVoiceActingVocalStaminaExercises: resolve(projectRoot, "zh/voice-acting-vocal-stamina-exercises/index.html"),
        zhVoiceActingAccentExercises: resolve(projectRoot, "zh/voice-acting-accent-exercises/index.html"),
        zhVoiceActingPhysicalityExercises: resolve(projectRoot, "zh/voice-acting-physicality-exercises/index.html"),
        zhVoiceActingVisualizationExercises: resolve(projectRoot, "zh/voice-acting-visualization-exercises/index.html"),
        zhVoiceActingComedyTimingExercises: resolve(projectRoot, "zh/voice-acting-comedy-timing-exercises/index.html"),
        zhVoiceActingCharacterSwitchingExercises: resolve(projectRoot, "zh/voice-acting-character-switching-exercises/index.html"),
        zhAudiobookNarrationExercises: resolve(projectRoot, "zh/audiobook-narration-exercises/index.html"),
        zhVoiceActingStatusExercises: resolve(projectRoot, "zh/voice-acting-status-exercises/index.html"),
        zhVoiceActingMemoryExercises: resolve(projectRoot, "zh/voice-acting-memory-exercises/index.html"),
        zhVoiceActingCharacterRelationshipExercises: resolve(projectRoot, "zh/voice-acting-character-relationship-exercises/index.html"),
        zhVoiceActingReactionExercises: resolve(projectRoot, "zh/voice-acting-reaction-exercises/index.html"),
        zhVoiceActingEffortSoundsExercises: resolve(projectRoot, "zh/voice-acting-effort-sounds-exercises/index.html"),
        zhVoiceActingObjectiveExercises: resolve(projectRoot, "zh/voice-acting-objective-exercises/index.html"),
        zhVoiceActingStakesExercises: resolve(projectRoot, "zh/voice-acting-stakes-exercises/index.html"),
        zhVoiceActingTakingDirectionExercises: resolve(projectRoot, "zh/voice-acting-taking-direction-exercises/index.html"),
        zhAdrVoiceActingExercises: resolve(projectRoot, "zh/adr-voice-acting-exercises/index.html"),
        zhELearningNarrationExercises: resolve(projectRoot, "zh/e-learning-narration-exercises/index.html"),
        zhAbout: resolve(projectRoot, "zh/about/index.html"),
        zhContact: resolve(projectRoot, "zh/contact/index.html"),
        zhPrivacy: resolve(projectRoot, "zh/privacy/index.html"),
        zhTerms: resolve(projectRoot, "zh/terms/index.html"),
        notFound: resolve(projectRoot, "404.html"),
      },
    },
  },
});
